language: node_js
node_js:
  - '8'
notifications:
  email:
  - jesusgraficap@gmail.com



before_install:
  - pip install --user codecov
install:
  - npm install
script:
  - npm run prepare
  - npm run test:ci
after_success:
  - codecov --file coverage/lcov.info --disable search
before_deploy:
  - cd dist
deploy:
  provider: npm
  email: $NPM_EMAIL
  skip_cleanup: true
  api_key:
    secure: $NPM_TOKEN
  on:
    branch: master
    tags: true

branches:
  only:
    - master
    - develop





