language: node_js
node_js:
  - '8'
notifications:
  email:
  - jesusgraficap@gmail.com

cache:
  directories:
  - node_modules
before_install:
  - npm update
install:
  - npm install
script:
  - npm run prepare
  - npm run test:ci
after_success:
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage

branches:
  only:
    - master
    - develop

