language: node_js
node_js:
  - '8'

notifications:
  email:
  - jesusgraficap@gmail.com

script:
  - npm run test
  - npm prepare
install:
  - npm install
branches:
  only:
    - master
    - develop

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
