language: node_js
node_js:
  - '8'
script:
  - yarn test
  - yarn prepare
install:
  - yarn install
branches:
  only:
    - master
    - develop

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
