language: node_js
node_js:
  - '8'
notifications:
  email:
  - jesusgraficap@gmail.com

before_install:
  - pip install --user codecov
install:
  - npm install
script:
  - npm run prepare
  - npm run test:ci
  - npm run coveralls
  - sonar-scanner
after_success:
  - codecov --file coverage/lcov.info --disable search

branches:
  only:
    - master
    - develop


addons:
  sonarcloud:
    organization: "jeiker26-github"
    token:
      secure: "$SONAR_TOKEN"
    branch:
      name: "$TRAVIS_BRANCH"


