language: node_js
node_js:
  - '8'
notifications:
  email:
  - jesusgraficap@gmail.com

install:
  - npm install
script:
  - npm run prepare
  - npm run test:ci
after_success:
  - npm run coveralls

branches:
  only:
    - master
    - develop

