language: node_js
node_js:
  - '8'
notifications:
  email:
  - jesusgraficap@gmail.com



before_install:
  - pip install --user codecov
  - sbt clean coverage test
install:
  - npm install
script:
  - npm run prepare
  - npm run test:ci
after_success:
  - codecov --file coverage/lcov.info --disable search
  - sbt coveralls

branches:
  only:
    - master
    - develop





